AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'node_modules/**/*'

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  IgnoredPatterns:
    - '\A\s*#'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'
